### PR TITLE
Added parameters for specifying iam_instance_profile and key_pair for new Launch configuration

### PR DESCRIPTION
**Pull request by Satyricon**

### CODE REVIEW

**Comment by Satyricon** [comment]
Fixed failing test

**Comment by Satyricon** [comment]
Did you have time t check this pull request?

**Comment by lserman** [comment]
Got a lot going on at work right now sorry haven't looked at it.

**Comment by lserman** [comment]
I'm just now coming back to maintain this repository using the new AWS SDK and AWS launch templates. I will not be maintaining the old ELBAS that relied on launch configurations and AWS SDK v1. Launch templates take care of these settings from within AWS instead of having to configure them inside of this gem, so I'll be closing this issue.

**Pull request closed without merging**
