### PR TITLE
Multi Region/Multi ASG

### PR DESCRIPTION
**Pull request by sixfeetover**
These changes allow for deploying to multiple regions and/or multiple autoscaling groups. Addresses #15.

This should be merged after #20, as it builds off of those commits. When #20 is merged in, I can rebase off of that before this gets merged.

### CODE REVIEW

**Comment by jamesbloomer** [comment]
I tried using the branch for this PR and found that it tried to connect to the servers using the private IP address. Is that something that you have seen? Maybe this is an artefact of the new SDK version?

**Comment by jamesbloomer** [comment]
I've been trying this PR, placing the autoscale call in an environment configuration file where a call to `server` used to be. It still however only updates one of the launch configurations.

eg.

```ruby
set :stage, :review

autoscale 'www', user: 'user', roles: %w(app db)
autoscale 'data', user: 'user', roles: %w(data)
```

Are you running `autoscale` inside a configuration file like that? It only updates the AMI and LC for the last `autoscale` in the file.

**Comment by sixfeetover** [comment]
That's true - it's the internal IP because our servers have no public IPs. They are private and only accessed through a bastion. We haven't tested on public because we don't have any - perhaps we can make it an option to use either internal IP or public DNS.

As to the ASG, we are deploying to the ASGs of the same name in different regions. Let me verify the behavior and get back to you.

**Comment by mmartell37** [comment]
I have verified locally that indeed a new AMi is created, and the launch configuration updated for, only the last ASG provided. I'm debugging now.

**Comment by mmartell37** [comment]
I've added support for multiple regions in #21 and tested in locally. This should also support multiple, different ASGs per region, but is not yet tested.

**Comment by jamesbloomer** [comment]
@mmartell37 I'm afraid that still doesn't work for the case of:

```ruby
autoscale 'www', user: 'user', roles: %w(app)
autoscale 'data', user: 'user', roles: %w(data)

set :aws_region, 'eu-west-1'
```

It creates the AMI and LC for the last autoscale statement.

**Comment by mmartell37** [comment]
@jamesbloomer Indeed, I missed an inner loop over ASGs in a given region. I've tested locally, but do not have a multi-ASG setup in a given region. Please try #21 again with my latest commit.

**Comment by jamesbloomer** [comment]
I've got that working now, so thanks a lot. A couple of points to note:

- My aws-sdk gem upgraded to 2.9.23 on an update and gave a error saying that the region wasn't set, when I pinned it back to 2.6.44 which is the version we're on in production everything was fine.
- The multiple AMIs created only have different names due to the timestamp which could potentially lead to issues if the creation is really quick.

**Comment by sixfeetover** [comment]
Since there's no activity here, and there's more stuff we wanted to do to this gem, I've forked this permanently as a new gem at https://github.com/sixfeetover/capistrano-asg.

@jamesbloomer Do you want to add your comments as an issue over there? PRs also welcome!

**Comment by lserman** [comment]
I'm just now coming back to maintain this repository using the new AWS SDK and AWS launch templates. I will not be maintaining the old ELBAS that relied on launch configurations and AWS SDK v1. It seems like @sixfeetover has moved the older versions onto a fork and that's fine by me, so I'm going to close this PR. Multi-region AMI creation is something I'd like to get into the new version eventually but isn't a priority for me personally at the moment. If someone wants to extract the AMI creation/launch template parts of this PR, update them for aws-sdk-v3, and make a new PR then I'll be glad to take a look at it and merge.

**Comment by Systho** [comment]
@lserman  How high a priority is it for you to allow single region but multiple ASG ?

**Comment by lserman** [comment]
Not personally motivated to do it right now, our setups all use one ASG per deploy. I will be more active in managing PRs etc though if someone else wants to take a shot.

**Pull request closed without merging**
