### PR TITLE
Upgrading to AWS SDK V2

### PR DESCRIPTION
**Pull request by mmartell37**
Upgraded source and tests to be compliant with AWS SDK V2. Tested in our production environment, works as expected.

### CODE REVIEW

**Comment by mmartell37** [comment]
Missing `aws_region` in TravisCI.

**Comment by mmartell37** [comment]
I don't like the previous solution with `fetch`, and I also want to update to Ruby 2.4.1.

**Comment by mmartell37** [comment]
Addresses #13. Also, see #21.

**Comment by lserman** [comment]
I'm just now coming back to maintain this repository using the new AWS SDK and AWS launch templates. I will not be maintaining the old ELBAS that relied on launch configurations and AWS SDK v1. I also have updated this repository to go straight from SDK v1 to v3 and that's what I will focus on going forward.

**Pull request closed without merging**
